// Generated by https://quicktype.io

export interface Inventory {
  title_id: number;
  title_iid: string;
  title_name: string;
  genre: Genre;
  rating: Rating;
  release_year: number;
  region: Genre | null;
  content_type: ContentType;
  episode_count: number;
  content_length: number;
  publish_timestamp: number;
  deliver_success_count: number;
  deliver_total_count: number;
  deliver_rate: number;
  approve_status: boolean;
  activate: boolean;
  cp_code: string;
  license_start: number;
  license_end: number;
  licensor: string;
  seasons: Season[];
}

export enum ContentType {
  Movie = 'Movie',
  Series = 'Series',
}

export interface Genre {
  code: string;
  name: string;
}

export enum Rating {
  D17 = 'D17+',
  D21 = 'D21+',
  R13 = 'R13+',
  Su = 'SU',
}

export interface Season {
  season_id: number;
  season_uuid: string;
  season_name: string;
  season_number: number;
  episode_count: number;
  publish_timestamp: number;
  activate: boolean;
  license_start: number;
  license_end: number;
  deliver_rate: number;
  cp_code: CpCode;
  licensor: Licensor;
  episodes: Episode[];
}

export enum CpCode {
  Empty = '',
  Iddci = 'IDDCI',
  Idiso = 'IDISO',
  Krkbs = 'KRKBS',
  Krkcc = 'KRKCC',
  Ruamc = 'RUAMC',
}

export interface Episode {
  episode_id: number;
  episode_uuid: string;
  episode_name: string;
  episode_number: number;
  publish_timestamp: number;
  activate: boolean;
  deliver_rate: number;
  content_length: number;
  cp_code: CpCode;
  licensor: Licensor;
}

export enum Licensor {
  Empty = '',
  Iddci = 'IDDCI',
  Idgen = 'IDGEN',
  Iflix = 'IFLIX',
  Ruamc = 'RUAMC',
}
